services:
#  db:
#    image: postgres:17
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: mydb
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - host.docker.internal:host-gateway
#    depends_on:
#      - db
    volumes:
      - ./backend:/app
      - /app/.venv/

#volumes:
#  postgres_data:
